# Generated by Django 3.1.2 on 2021-02-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400)),
                ('Author', models.CharField(max_length=400)),
                ('Code', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=400)),
            ],
        ),
    ]
