# Generated by Django 3.1.2 on 2021-02-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fullname',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
